// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ActivitiesDocumentDataSlicesSlice = ActivitySummarySlice;

/**
 * Content for Kunsthalle Activities documents
 */
interface ActivitiesDocumentData {
  /**
   * Title field in *Kunsthalle Activities*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Activities
   * - **API ID Path**: activities.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * No activities title field in *Kunsthalle Activities*
   *
   * - **Field Type**: Text
   * - **Placeholder**: No activities at the moment
   * - **API ID Path**: activities.no_activities_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  no_activities_title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Kunsthalle Activities*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: activities.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ActivitiesDocumentDataSlicesSlice> /**
   * Meta Title field in *Kunsthalle Activities*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: activities.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Kunsthalle Activities*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: activities.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Kunsthalle Activities*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: activities.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Kunsthalle Activities document from Prismic
 *
 * - **API ID**: `activities`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ActivitiesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ActivitiesDocumentData>,
    "activities",
    Lang
  >;

/**
 * Item in *Activity Page → Event types*
 */
export interface ActivityDetailDocumentDataEventTypesItem {
  /**
   * Event Type field in *Activity Page → Event types*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select one
   * - **API ID Path**: activity_detail.event_types[].event_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  event_type: prismic.SelectField<"Event" | "Residency" | "Workshop">;
}

/**
 * Item in *Activity Page → Slider Images*
 */
export interface ActivityDetailDocumentDataSliderImagesItem {
  /**
   * Image field in *Activity Page → Slider Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: activity_detail.slider_images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Caption field in *Activity Page → Slider Images*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: activity_detail.slider_images[].caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  caption: prismic.KeyTextField;
}

type ActivityDetailDocumentDataSlicesSlice = never;

/**
 * Content for Activity Page documents
 */
interface ActivityDetailDocumentData {
  /**
   * Event types field in *Activity Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: activity_detail.event_types[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  event_types: prismic.GroupField<
    Simplify<ActivityDetailDocumentDataEventTypesItem>
  >;

  /**
   * Title field in *Activity Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Soundtrack to a Coup d’Etat
   * - **API ID Path**: activity_detail.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *Activity Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Johan Grimonprez
   * - **API ID Path**: activity_detail.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Date and time field in *Activity Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: 09 Nov 2024, 19:30
   * - **API ID Path**: activity_detail.date_and_time
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  date_and_time: prismic.RichTextField;

  /**
   * Type field in *Activity Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Upcoming/Current/Past
   * - **API ID Path**: activity_detail.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<"Upcoming" | "Current" | "Past">;

  /**
   * Slider Images field in *Activity Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: activity_detail.slider_images[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  slider_images: prismic.GroupField<
    Simplify<ActivityDetailDocumentDataSliderImagesItem>
  >;

  /**
   * Description field in *Activity Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Bangkok Kunsthalle in collaboration with Doc Club present the Thai premiere of...
   * - **API ID Path**: activity_detail.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Slice Zone field in *Activity Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: activity_detail.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ActivityDetailDocumentDataSlicesSlice> /**
   * Meta Title field in *Activity Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: activity_detail.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Activity Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: activity_detail.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Activity Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: activity_detail.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Activity Page document from Prismic
 *
 * - **API ID**: `activity_detail`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ActivityDetailDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ActivityDetailDocumentData>,
    "activity_detail",
    Lang
  >;

/**
 * Item in *Exhibition Page → Slider Images*
 */
export interface ExhibitionDetailDocumentDataSliderImagesItem {
  /**
   * Image field in *Exhibition Page → Slider Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: exhibition_detail.slider_images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Caption field in *Exhibition Page → Slider Images*
   *
   * - **Field Type**: Text
   * - **Placeholder**: This is a picture of...
   * - **API ID Path**: exhibition_detail.slider_images[].caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  caption: prismic.KeyTextField;
}

type ExhibitionDetailDocumentDataSlicesSlice = never;

/**
 * Content for Exhibition Page documents
 */
interface ExhibitionDetailDocumentData {
  /**
   * Title field in *Exhibition Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Walking in Nature
   * - **API ID Path**: exhibition_detail.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *Exhibition Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Richard Long
   * - **API ID Path**: exhibition_detail.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Date and time field in *Exhibition Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: 23 Oct - 22 Dec 2024
   * - **API ID Path**: exhibition_detail.date_and_time
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  date_and_time: prismic.RichTextField;

  /**
   * Type field in *Exhibition Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Upcoming/Current/Past
   * - **API ID Path**: exhibition_detail.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<"Upcoming" | "Current" | "Past">;

  /**
   * Slider Images field in *Exhibition Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: exhibition_detail.slider_images[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  slider_images: prismic.GroupField<
    Simplify<ExhibitionDetailDocumentDataSliderImagesItem>
  >;

  /**
   * Description field in *Exhibition Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: This exclusive Exhibition/Event is hosted by Art Forest...
   * - **API ID Path**: exhibition_detail.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Slice Zone field in *Exhibition Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: exhibition_detail.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ExhibitionDetailDocumentDataSlicesSlice> /**
   * Meta Title field in *Exhibition Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: exhibition_detail.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Exhibition Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: exhibition_detail.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Exhibition Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: exhibition_detail.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Exhibition Page document from Prismic
 *
 * - **API ID**: `exhibition_detail`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ExhibitionDetailDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ExhibitionDetailDocumentData>,
    "exhibition_detail",
    Lang
  >;

type ExhibitionsDocumentDataSlicesSlice = ExhibitionSummarySlice;

/**
 * Content for Kunsthalle Exhibitions documents
 */
interface ExhibitionsDocumentData {
  /**
   * No exhibitions title field in *Kunsthalle Exhibitions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: No exhibitions at the moment
   * - **API ID Path**: exhibitions.no_exhibitions_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  no_exhibitions_title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Kunsthalle Exhibitions*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: exhibitions.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ExhibitionsDocumentDataSlicesSlice> /**
   * Meta Title field in *Kunsthalle Exhibitions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: exhibitions.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Kunsthalle Exhibitions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: exhibitions.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Kunsthalle Exhibitions*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: exhibitions.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Kunsthalle Exhibitions document from Prismic
 *
 * - **API ID**: `exhibitions`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ExhibitionsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ExhibitionsDocumentData>,
    "exhibitions",
    Lang
  >;

type HomePageDocumentDataSlicesSlice = never;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * KYAF Background Image field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.kyaf_background_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  kyaf_background_image: prismic.ImageField<never>;

  /**
   * BKKK Background Image field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.bkkk_background_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bkkk_background_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

type KunsthalleAboutHomeDocumentDataSlicesSlice =
  | VisitSlice
  | TeamSlice
  | ContactFormSlice
  | AboutUsSlice;

/**
 * Content for Kunsthalle About Home documents
 */
interface KunsthalleAboutHomeDocumentData {
  /**
   * Title field in *Kunsthalle About Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: About
   * - **API ID Path**: kunsthalle_about_home.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Kunsthalle About Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: kunsthalle_about_home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<KunsthalleAboutHomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Kunsthalle About Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: kunsthalle_about_home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Kunsthalle About Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: kunsthalle_about_home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Kunsthalle About Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: kunsthalle_about_home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Kunsthalle About Home document from Prismic
 *
 * - **API ID**: `kunsthalle_about_home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type KunsthalleAboutHomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<KunsthalleAboutHomeDocumentData>,
    "kunsthalle_about_home",
    Lang
  >;

type KyafAboutHomeDocumentDataSlicesSlice =
  | ContactFormSlice
  | VisitSlice
  | TeamSlice
  | AboutUsSlice;

/**
 * Content for kyaf_about_home documents
 */
interface KyafAboutHomeDocumentData {
  /**
   * Title field in *kyaf_about_home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title
   * - **API ID Path**: kyaf_about_home.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *kyaf_about_home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: kyaf_about_home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<KyafAboutHomeDocumentDataSlicesSlice> /**
   * Meta Title field in *kyaf_about_home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: kyaf_about_home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *kyaf_about_home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: kyaf_about_home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *kyaf_about_home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: kyaf_about_home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * kyaf_about_home document from Prismic
 *
 * - **API ID**: `kyaf_about_home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type KyafAboutHomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<KyafAboutHomeDocumentData>,
    "kyaf_about_home",
    Lang
  >;

type KyafActivitiesDocumentDataSlicesSlice = ActivitySummarySlice;

/**
 * Content for KYAF activities documents
 */
interface KyafActivitiesDocumentData {
  /**
   * Title field in *KYAF activities*
   *
   * - **Field Type**: Text
   * - **Placeholder**: title
   * - **API ID Path**: kyaf_activities.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * No activities title field in *KYAF activities*
   *
   * - **Field Type**: Text
   * - **Placeholder**: There are no activities at the moment
   * - **API ID Path**: kyaf_activities.no_activities_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  no_activities_title: prismic.KeyTextField;

  /**
   * Slice Zone field in *KYAF activities*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: kyaf_activities.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<KyafActivitiesDocumentDataSlicesSlice> /**
   * Meta Title field in *KYAF activities*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: kyaf_activities.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *KYAF activities*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: kyaf_activities.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *KYAF activities*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: kyaf_activities.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * KYAF activities document from Prismic
 *
 * - **API ID**: `kyaf_activities`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type KyafActivitiesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<KyafActivitiesDocumentData>,
    "kyaf_activities",
    Lang
  >;

type KyafExhibitionsDocumentDataSlicesSlice = ExhibitionSummarySlice;

/**
 * Content for KYAF Exhibitions documents
 */
interface KyafExhibitionsDocumentData {
  /**
   * No exhibitions title field in *KYAF Exhibitions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: No exhibitions at the moment
   * - **API ID Path**: kyaf_exhibitions.no_exhibitions_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  no_exhibitions_title: prismic.KeyTextField;

  /**
   * Slice Zone field in *KYAF Exhibitions*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: kyaf_exhibitions.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<KyafExhibitionsDocumentDataSlicesSlice> /**
   * Meta Title field in *KYAF Exhibitions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: kyaf_exhibitions.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *KYAF Exhibitions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: kyaf_exhibitions.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *KYAF Exhibitions*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: kyaf_exhibitions.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * KYAF Exhibitions document from Prismic
 *
 * - **API ID**: `kyaf_exhibitions`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type KyafExhibitionsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<KyafExhibitionsDocumentData>,
    "kyaf_exhibitions",
    Lang
  >;

export type AllDocumentTypes =
  | ActivitiesDocument
  | ActivityDetailDocument
  | ExhibitionDetailDocument
  | ExhibitionsDocument
  | HomePageDocument
  | KunsthalleAboutHomeDocument
  | KyafAboutHomeDocument
  | KyafActivitiesDocument
  | KyafExhibitionsDocument;

/**
 * Primary content in *AboutUs → Default → Primary*
 */
export interface AboutUsSliceDefaultPrimary {
  /**
   * Title field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: About us
   * - **API ID Path**: about_us.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: We are a...
   * - **API ID Path**: about_us.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for AboutUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutUsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutUs*
 */
type AboutUsSliceVariation = AboutUsSliceDefault;

/**
 * AboutUs Shared Slice
 *
 * - **API ID**: `about_us`
 * - **Description**: AboutUs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsSlice = prismic.SharedSlice<
  "about_us",
  AboutUsSliceVariation
>;

/**
 * Item in *ActivitySummary → Default → Primary → Event types*
 */
export interface ActivitySummarySliceDefaultPrimaryEventTypesItem {
  /**
   * Event type field in *ActivitySummary → Default → Primary → Event types*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select one
   * - **API ID Path**: activity_summary.default.primary.event_types[].event_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  event_type: prismic.SelectField<"Event" | "Residency" | "Workshop">;
}

/**
 * Primary content in *ActivitySummary → Default → Primary*
 */
export interface ActivitySummarySliceDefaultPrimary {
  /**
   * Event types field in *ActivitySummary → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: activity_summary.default.primary.event_types[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  event_types: prismic.GroupField<
    Simplify<ActivitySummarySliceDefaultPrimaryEventTypesItem>
  >;

  /**
   * Title field in *ActivitySummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: We don't have many days
   * - **API ID Path**: activity_summary.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *ActivitySummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: James Gallego Olivo
   * - **API ID Path**: activity_summary.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * date and time field in *ActivitySummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: 13 Aug 2024, 16:30
   * - **API ID Path**: activity_summary.default.primary.date_and_time
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  date_and_time: prismic.RichTextField;

  /**
   * Main image field in *ActivitySummary → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: activity_summary.default.primary.main_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  main_image: prismic.ImageField<never>;

  /**
   * Type field in *ActivitySummary → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Upcoming/Current/Past
   * - **API ID Path**: activity_summary.default.primary.type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<"Upcoming" | "Current" | "Past">;

  /**
   * Activity Detail field in *ActivitySummary → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: activity_summary.default.primary.activity_detail
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  activity_detail: prismic.ContentRelationshipField<"activity_detail">;
}

/**
 * Default variation for ActivitySummary Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ActivitySummarySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ActivitySummarySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ActivitySummary*
 */
type ActivitySummarySliceVariation = ActivitySummarySliceDefault;

/**
 * ActivitySummary Shared Slice
 *
 * - **API ID**: `activity_summary`
 * - **Description**: ActivitySummary
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ActivitySummarySlice = prismic.SharedSlice<
  "activity_summary",
  ActivitySummarySliceVariation
>;

/**
 * Item in *ContactForm → Default → Primary → Form field*
 */
export interface ContactFormSliceDefaultPrimaryFormFieldItem {
  /**
   * Label field in *ContactForm → Default → Primary → Form field*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Name
   * - **API ID Path**: contact_form.default.primary.form_field[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Form type field in *ContactForm → Default → Primary → Form field*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Text/Multiline/Email
   * - **API ID Path**: contact_form.default.primary.form_field[].form_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  form_type: prismic.SelectField<"Text" | "Multiline" | "Email">;
}

/**
 * Primary content in *ContactForm → Default → Primary*
 */
export interface ContactFormSliceDefaultPrimary {
  /**
   * Title field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Contact
   * - **API ID Path**: contact_form.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Form field field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.form_field[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  form_field: prismic.GroupField<
    Simplify<ContactFormSliceDefaultPrimaryFormFieldItem>
  >;

  /**
   * Submit button label field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Submit
   * - **API ID Path**: contact_form.default.primary.submit_button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  submit_button_label: prismic.KeyTextField;
}

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: ContactForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSlice = prismic.SharedSlice<
  "contact_form",
  ContactFormSliceVariation
>;

/**
 * Primary content in *ExhibitionSummary → Default → Primary*
 */
export interface ExhibitionSummarySliceDefaultPrimary {
  /**
   * Title field in *ExhibitionSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Title of Exhibition
   * - **API ID Path**: exhibition_summary.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *ExhibitionSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Subtitle of Exhibition
   * - **API ID Path**: exhibition_summary.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * date and time field in *ExhibitionSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: 12 Jan - 10 Mar 2024
   * - **API ID Path**: exhibition_summary.default.primary.date_and_time
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  date_and_time: prismic.RichTextField;

  /**
   * Main image field in *ExhibitionSummary → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: exhibition_summary.default.primary.main_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  main_image: prismic.ImageField<never>;

  /**
   * Type field in *ExhibitionSummary → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Upcoming/Current/Past
   * - **API ID Path**: exhibition_summary.default.primary.type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<"Upcoming" | "Current" | "Past">;

  /**
   * Exhibition Detail field in *ExhibitionSummary → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: exhibition_summary.default.primary.exhibition_detail
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  exhibition_detail: prismic.ContentRelationshipField<"exhibition_detail">;
}

/**
 * Default variation for ExhibitionSummary Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExhibitionSummarySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ExhibitionSummarySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ExhibitionSummary*
 */
type ExhibitionSummarySliceVariation = ExhibitionSummarySliceDefault;

/**
 * ExhibitionSummary Shared Slice
 *
 * - **API ID**: `exhibition_summary`
 * - **Description**: ExhibitionSummary
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExhibitionSummarySlice = prismic.SharedSlice<
  "exhibition_summary",
  ExhibitionSummarySliceVariation
>;

/**
 * Item in *Team → Default → Primary → Board Members*
 */
export interface TeamSliceDefaultPrimaryBoardMembersItem {
  /**
   * Name field in *Team → Default → Primary → Board Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Name
   * - **API ID Path**: team.default.primary.board_members[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Title field in *Team → Default → Primary → Board Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: title
   * - **API ID Path**: team.default.primary.board_members[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Email field in *Team → Default → Primary → Board Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: email
   * - **API ID Path**: team.default.primary.board_members[].email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Description field in *Team → Default → Primary → Board Members*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.board_members[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Item in *Team → Default → Primary → Members*
 */
export interface TeamSliceDefaultPrimaryMembersItem {
  /**
   * Name field in *Team → Default → Primary → Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Marisa Chearavanont
   * - **API ID Path**: team.default.primary.members[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Title field in *Team → Default → Primary → Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Founder / President
   * - **API ID Path**: team.default.primary.members[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Email field in *Team → Default → Primary → Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**:  marisa.c@khaoyaiart.com
   * - **API ID Path**: team.default.primary.members[].email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Description field in *Team → Default → Primary → Members*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Born in Thailand...
   * - **API ID Path**: team.default.primary.members[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Item in *Team → Default → Primary → Director's Circle Members*
 */
export interface TeamSliceDefaultPrimaryDirectorsCircleMembersItem {
  /**
   * Name field in *Team → Default → Primary → Director's Circle Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.directors_circle_members[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Title field in *Team → Default → Primary → Director's Circle Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.directors_circle_members[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Email field in *Team → Default → Primary → Director's Circle Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.directors_circle_members[].email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Description field in *Team → Default → Primary → Director's Circle Members*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.directors_circle_members[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Team → Default → Primary*
 */
export interface TeamSliceDefaultPrimary {
  /**
   * Board Title field in *Team → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Board
   * - **API ID Path**: team.default.primary.board_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  board_title: prismic.KeyTextField;

  /**
   * Board Members field in *Team → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.board_members[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  board_members: prismic.GroupField<
    Simplify<TeamSliceDefaultPrimaryBoardMembersItem>
  >;

  /**
   * Team Title field in *Team → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Team
   * - **API ID Path**: team.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Members field in *Team → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.members[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  members: prismic.GroupField<Simplify<TeamSliceDefaultPrimaryMembersItem>>;

  /**
   * Director's Circle Title field in *Team → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Director's Circle
   * - **API ID Path**: team.default.primary.directors_circle_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  directors_circle_title: prismic.KeyTextField;

  /**
   * Director's Circle Members field in *Team → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.directors_circle_members[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  directors_circle_members: prismic.GroupField<
    Simplify<TeamSliceDefaultPrimaryDirectorsCircleMembersItem>
  >;
}

/**
 * Default variation for Team Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Team*
 */
type TeamSliceVariation = TeamSliceDefault;

/**
 * Team Shared Slice
 *
 * - **API ID**: `team`
 * - **Description**: Team
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSlice = prismic.SharedSlice<"team", TeamSliceVariation>;

/**
 * Primary content in *Visit → Default → Primary*
 */
export interface VisitSliceDefaultPrimary {
  /**
   * Title field in *Visit → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Visit
   * - **API ID Path**: visit.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Address and opening hours field in *Visit → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: visit.default.primary.address_and_opening_hours
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  address_and_opening_hours: prismic.RichTextField;

  /**
   * Google Maps embed src field in *Visit → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://www.google.com/maps/embed?pb=...
   * - **API ID Path**: visit.default.primary.google_maps_embed_src
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  google_maps_embed_src: prismic.LinkField;
}

/**
 * Default variation for Visit Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VisitSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VisitSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Visit*
 */
type VisitSliceVariation = VisitSliceDefault;

/**
 * Visit Shared Slice
 *
 * - **API ID**: `visit`
 * - **Description**: Visit
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VisitSlice = prismic.SharedSlice<"visit", VisitSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ActivitiesDocument,
      ActivitiesDocumentData,
      ActivitiesDocumentDataSlicesSlice,
      ActivityDetailDocument,
      ActivityDetailDocumentData,
      ActivityDetailDocumentDataEventTypesItem,
      ActivityDetailDocumentDataSliderImagesItem,
      ActivityDetailDocumentDataSlicesSlice,
      ExhibitionDetailDocument,
      ExhibitionDetailDocumentData,
      ExhibitionDetailDocumentDataSliderImagesItem,
      ExhibitionDetailDocumentDataSlicesSlice,
      ExhibitionsDocument,
      ExhibitionsDocumentData,
      ExhibitionsDocumentDataSlicesSlice,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      KunsthalleAboutHomeDocument,
      KunsthalleAboutHomeDocumentData,
      KunsthalleAboutHomeDocumentDataSlicesSlice,
      KyafAboutHomeDocument,
      KyafAboutHomeDocumentData,
      KyafAboutHomeDocumentDataSlicesSlice,
      KyafActivitiesDocument,
      KyafActivitiesDocumentData,
      KyafActivitiesDocumentDataSlicesSlice,
      KyafExhibitionsDocument,
      KyafExhibitionsDocumentData,
      KyafExhibitionsDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutUsSlice,
      AboutUsSliceDefaultPrimary,
      AboutUsSliceVariation,
      AboutUsSliceDefault,
      ActivitySummarySlice,
      ActivitySummarySliceDefaultPrimaryEventTypesItem,
      ActivitySummarySliceDefaultPrimary,
      ActivitySummarySliceVariation,
      ActivitySummarySliceDefault,
      ContactFormSlice,
      ContactFormSliceDefaultPrimaryFormFieldItem,
      ContactFormSliceDefaultPrimary,
      ContactFormSliceVariation,
      ContactFormSliceDefault,
      ExhibitionSummarySlice,
      ExhibitionSummarySliceDefaultPrimary,
      ExhibitionSummarySliceVariation,
      ExhibitionSummarySliceDefault,
      TeamSlice,
      TeamSliceDefaultPrimaryBoardMembersItem,
      TeamSliceDefaultPrimaryMembersItem,
      TeamSliceDefaultPrimaryDirectorsCircleMembersItem,
      TeamSliceDefaultPrimary,
      TeamSliceVariation,
      TeamSliceDefault,
      VisitSlice,
      VisitSliceDefaultPrimary,
      VisitSliceVariation,
      VisitSliceDefault,
    };
  }
}
