// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_us: dynamic(() => import("./AboutUs")),
  activity_summary: dynamic(() => import("./ActivitySummary")),
  contact_form: dynamic(() => import("./ContactForm")),
  exhibition_summary: dynamic(() => import("./ExhibitionSummary")),
  team: dynamic(() => import("./Team")),
  visit: dynamic(() => import("./Visit")),
};
